Project-Reclass/toynet-react

.github/PULL_REQUEST_TEMPLATE.md

Trello: https://trello.com/c/KdA0vqxI/205-github-process
None
None, no code change
* It will be tested in the next Pull Request.

Add Engineer Workflow Document to PR Template

---

package-lock.json
package.json
src/App.test.js
tests/functions.js
tests/functions.test.js

Trello Ticket: https://trello.com/c/qev9lt2k/210-frontend-add-unit-test-demo-to-toynet
**Dependencies
(https://docs.google.com/document/d/1CM6OA2nlhI3DHnHdDEgySukx_tZ_wsG-C2YgraZRvJA/edit#heading=h.czpk4cbi7z4g)**
N/A
**Explain Impact on DB
(https://docs.google.com/document/d/1CM6OA2nlhI3DHnHdDEgySukx_tZ_wsG-C2YgraZRvJA/edit#heading=h.285lgcs4z84o)**
N/A
How did you test this? List of actions & expected behavior with helpful …

jest unit test example

---

README.md

Trello Ticket: n/a
Additional Notes: to test heroku deployment
If this change is …

heroku link

---

.github/workflows/main.yml
tests/functions.test.js

Trello Ticket: https://trello.com/c/X9Jegfo7/222-setup-github-actions-for-unit-tests-in-jest
**Testing:**
- Good tests pass: https://github.com/Project-Reclass/toynet-react/actions/runs/171748110
- Bad tests fail: https://github.com/Project-Reclass/toynet-react/actions/runs/171761737
**Additional Notes:**
- No react code change
- `on: push` by itself had undesired behavior of running two tests every commit since `on: pull_request: [ master ]` appears to take care of the PR updates -> changed to `on: push: [master]`

Setup Automated Jest runs

---

src/Emulator/Emulator.css
src/Emulator/Emulator.js
src/Emulator/Instructions/Instructions.css
src/Emulator/Instructions/Instructions.js
src/Emulator/Tabs/Configure/Configure.js
src/Emulator/Tabs/Console/Console.js
src/Emulator/Tabs/History/History.js
src/Emulator/Tabs/Tabs.css
src/Emulator/Tabs/Tabs.js
src/Emulator/Visuals/Visuals.css

Trello Ticket: None
Additional Notes: Separated wireframe reconstruction from my work on the configure tab
**[Dependencies](https://docs.google.com/document/d/1CM6OA2nlhI3DHnHdDEgySukx_tZ_wsG-C2YgraZRvJA/edit#heading=h.czpk4cbi7z4g)** None
**[Explain Impact on DB](https://docs.google.com/document/d/1CM6OA2nlhI3DHnHdDEgySukx_tZ_wsG-C2YgraZRvJA/edit#heading=h.285lgcs4z84o)** None
**[Testing](https://docs.google.com/document/d/1CM6OA2nlhI3DHnHdDEgySukx_tZ_wsG-C2YgraZRvJA/edit#heading=h.rs692kr58cf8)** None
How did you test this? List of actions & expected behavior with helpful screenshots for reviewer: N/A
If this change is performance related, please document what tests were / should be done to verify improvement: N/A

Isolate wireframe reconstruction from configure

---

.github/workflows/main.yml
.gitignore
package-lock.json
package.json
src/App.js
src/Emulator/Emulator.js
src/Emulator/Tabs/Configure/Configure.js
src/Emulator/Tabs/Console/Console.js
src/Emulator/Tabs/History/History.js
src/Emulator/Tabs/Tabs.js
src/Header/Header.js
src/index.js

Trello Ticket: [DEFINE: Javascript Quality Checks](https://trello.com/c/1i0JIlQa/175-define-javascript-quality-checks)
Resolves linter enforcement objective for linked trello ticket.
N/A
N/A
Adds `lint` job in the `CI` workflow

Javascript Quality Checks - Linter

---

.dockerignore
Dockerfile
docker-entrypoint.sh

Trello Ticket: https://trello.com/c/hMdoQfnJ/251-dockerize-toynet-react
This PR adds the initial Dockerfile for the frontend of toynet-react.
[Related ticket](https://trello.com/c/dphaKH8a/252-dockerize-toynet-django)
N/A
N/A
Image built and tested on local machine.

Adds Dockerfile

---

src/App.tsx
src/Emulator/Instructions/Instructions.css

Trello Ticket: Garret's styling changes
If this change is …

Instruction styling

---

package-lock.json
package.json
src/Emulator/EmulatorProvider.tsx
src/Emulator/Tabs/ConfigureTab/DeviceContainer/Device/Device.css
src/Emulator/Tabs/ConfigureTab/DeviceContainer/Device/Device.tsx
src/Emulator/Tabs/ConfigureTab/DeviceContainer/Device/linkValidators.ts
src/Emulator/Tabs/ConfigureTab/DeviceContainer/DeviceContainer.css
src/Emulator/Tabs/ConfigureTab/DeviceContainer/DeviceContainer.tsx
src/Emulator/Visuals/Visuals.tsx
src/Emulator/useTopology.ts
src/__tests__/Emulator/EmulatorProvider.test.jsx
src/__tests__/Emulator/Tabs/ConfigureTab/DeviceContainer/Device/Device.test.jsx
src/__tests__/Emulator/Tabs/ConfigureTab/DeviceContainer/Device/__snapshots__/Device.test.jsx.snap
src/__tests__/Emulator/Tabs/ConfigureTab/DeviceContainer/DeviceContainer.test.jsx
src/__tests__/Emulator/Tabs/ConfigureTab/DeviceContainer/__snapshots__/DeviceContainer.test.jsx.snap
src/__tests__/Emulator/Tabs/ConfigureTab/__snapshots__/ConfigureTab.test.jsx.snap
src/__tests__/Emulator/__snapshots__/Emulator.test.jsx.snap
src/common/api/topology/hooks.ts
src/common/api/topology/requests.ts
src/common/types.ts
src/common/utils.ts
src/index.tsx

Trello Ticket: https://trello.com/c/1CtVFWHg/272-configure-tab-dragging-for-links
This PR adds the initial drag-n-drop configuration of devices and relevant tests. This PR also allows the image panel to update appropriately whenever there is an image update.
A side effect of this PR is updating Jest to the latest version. This was needed to properly test drag-n-drop of components.
[Immer](https://github.com/immerjs/immer) was added as part of this PR to help make managing state updates easier.
[React-DnD](https://github.com/react-dnd/react-dnd) was added to handle drag and drop of components. …

DnD to configure links

---

src/App.tsx

**Module 1**
Modifying Topology
**Objective**
Add and remove devices and their connections.
**Tasks**
1. Add a Host (h3)
2. Attach h3 to s2
3. Detach h3 from s2
4. Remove h2

Update Instructions for ToyNet Demo

---

src/App.tsx
src/FeatureFlags/FeatureFlags.tsx
src/FeatureFlags/flags.ts
src/FeatureFlags/index.ts
src/Header/Header.tsx

Trello Ticket: N/A
This PR adds the feature flag concept using a react context and also removes the SideNav until the feature is ready.
N/A

Adds feature flags and removes sidebar

---

src/App.css
src/App.tsx
src/Emulator/Emulator.css
src/Emulator/Emulator.tsx
src/Emulator/Instructions/Instructions.css
src/Emulator/Instructions/Instructions.tsx
src/Emulator/Tabs/ConfigureTab/ConfigureTab.css
src/Emulator/Tabs/ConfigureTab/DeviceContainer/Device/Device.css
src/Emulator/Tabs/ConfigureTab/DeviceContainer/Device/Device.tsx
src/Emulator/Tabs/ConfigureTab/DeviceContainer/DeviceContainer.css
src/Emulator/Visuals/Visuals.css
src/Emulator/Visuals/Visuals.tsx
src/FeatureFlags/FeatureFlags.tsx
src/FeatureFlags/flags.ts
src/FeatureFlags/index.ts
src/Header/Header.css
src/Header/Header.tsx
src/__tests__/Emulator/Tabs/ConfigureTab/DeviceContainer/Device/__snapshots__/Device.test.jsx.snap
src/__tests__/Emulator/Tabs/ConfigureTab/DeviceContainer/__snapshots__/DeviceContainer.test.jsx.snap
src/__tests__/Emulator/Tabs/ConfigureTab/__snapshots__/ConfigureTab.test.jsx.snap
src/__tests__/Emulator/__snapshots__/Emulator.test.jsx.snap
src/assets/v2-buttons/center-image.svg
src/assets/v2-buttons/eye-hide.svg
src/assets/v2-buttons/eye-show.svg
src/assets/v2-buttons/minus-zoom.svg
src/assets/v2-buttons/plus-zoom.svg

Trello Ticket: https://trello.com/c/T6OB4kCj/328-image-panel-buttons-need-a-contrasting-background
This PR fixes several styling issues within the emulator including [image panel buttons need a contrasting background](https://trello.com/c/T6OB4kCj/328-image-panel-buttons-need-a-contrasting-background)
**What's in this PR**
- Re-adds back to site
- Updates device scroll bar to be inside container
- Fixes styling of the Visuals and Tabs to be responsive
- Fixes padding on device names
- Fixes issue where the icons were hidden in visual
- Fixes issue where a lot of devices looks weird
Depends on …

Fix styling

---

src/Emulator/Tabs/ConfigureTab/DeviceContainer/Device/Device.css
src/Emulator/Tabs/ConfigureTab/DeviceContainer/Device/linkValidators.ts
src/Emulator/Visuals/Visuals.css
src/__tests__/Emulator/Tabs/ConfigureTab/DeviceContainer/Device/Device.test.jsx

Trello Ticket:
This PR disables switch to switch links which seem to cause a cycle in the network tree.
It also changes a small styling issue where the icons in the visual panel were not aligned appropriately.

Disables switch to switch links

---

src/App.tsx
src/Emulator/Emulator.tsx
src/__tests__/Emulator/Emulator.test.jsx
src/__tests__/Emulator/__snapshots__/Emulator.test.jsx.snap

Trello Ticket: https://trello.com/c/xfFWEz8R/358-decouple-any-mock-data-from-apptsx
Additional Notes: Placed mock data into Emulator because it's only used in that component
How did …

Decouple mock data

---

src/SplashScreen/SplashAbout/SplashAbout.tsx

Trello Ticket: https://trello.com/c/X08zxKBb/368-update-about-section-content
How did you test this? List of actions & expected behavior with helpful screenshots for …

Updated About Section Content

---

src/App.tsx
src/ModuleList/Lesson/Lesson.tsx
src/ModuleList/Lesson/index.ts

Trello Ticket: https://trello.com/c/0nmXJzja/360-create-blank-lesson-page-and-add-react-route
How did you test this? List of actions & expected behavior with helpful …

Create Blank Lesson

---

src/App.tsx
src/ModuleList/Values/Values.tsx
src/ModuleList/Values/index.ts
src/__tests__/ModuleList/Values/Values.test.jsx
src/__tests__/ModuleList/Values/__snapshots__/Values.test.jsx.snap

Trello Ticket: https://trello.com/c/rEC2e6Ly/369-values-submodule
If …

Add Values submodule

---

.github/workflows/cd-stage.yml
.github/workflows/cd.yml

Trello Ticket:
If this change is performance related, please …

taggy tay tay

---

src/SplashScreen/SplashAbout/SplashAbout.tsx

Trello Ticket:
Fixes navigation on splash screen for about section

Fix about navigation on splash screen

---

.github/workflows/cd.yml

Trello Ticket:
If this change is performance related, please …

toynet-react -> toynet-react-repo

---

src/Emulator/Tabs/ConfigureTab/DeviceContainer/DeviceContainer.tsx
src/__tests__/Emulator/Tabs/ConfigureTab/DeviceContainer/__snapshots__/DeviceContainer.test.jsx.snap
src/__tests__/Emulator/Tabs/ConfigureTab/__snapshots__/ConfigureTab.test.jsx.snap
src/__tests__/Emulator/__snapshots__/Emulator.test.jsx.snap

Trello Ticket: https://trello.com/c/z59gEjiw/384-emulator-make-configuration-tab-works-space-vertically-taller
How did you test this? List of actions & expected …

emulator: enlarge configuration tab

---

package.json
src/ModuleList/Quiz/Quiz.tsx
src/ModuleList/Quiz/QuizModal.tsx
src/ModuleList/Quiz/styled.ts
src/__tests__/ModuleList/Quiz/Quiz.test.jsx
src/__tests__/ModuleList/Quiz/QuizModal.test.jsx
src/__tests__/ModuleList/Quiz/__snapshots__/Quiz.test.jsx.snap
src/common/components/LoadingContainer.tsx
src/index.css

Trello Ticket: https://trello.com/c/eceh0OeF/391-add-modal-for-quiz
Additional Notes: This PR adds the modal for the quiz. When a user submits a quiz the modal is shown and gives the user the option to try the quiz again to complete the quiz.

Quiz modal

---

src/Emulator/Visuals/Visuals.tsx

Trello Ticket: https://trello.com/c/u8IvELSz/383-emulator-image-panel-should-start-centered
How did you test this? List of actions & expected behavior with helpful …

Visual panel centered

---

src/Login/Login.tsx
src/__tests__/Login/Login.test.jsx
src/__tests__/Login/__snapshots__/Login.test.jsx.snap

Trello Ticket: https://trello.com/c/ucmS5CYU/412-login-screen-make-input-red-when-invalid-input
Additional Notes:  this PR adds red borders around invalid inputs for username & password

red borders for invalid inputs

---

src/Emulator/Tabs/ConfigureTab/DeviceContainer/DeviceContainer.tsx

Trello Ticket: https://trello.com/c/7yO4f463/395-emulator-creating-links-causes-the-panel-to-jump
How did you test this? List of actions & expected behavior with …

fixed panel jumping

---

package-lock.json
package.json
src/Curriculum/Value/Value.tsx
src/Curriculum/withMockData.tsx
src/FeatureFlags/flags.ts
tsconfig.json

@theo-commits I fixed the issues

Fixes security vulns

---

src/Curriculum/Quiz/Quiz.tsx
src/__tests__/ModuleList/Quiz/Quiz.test.jsx
src/common/api/curriculum/quiz/requests.ts

Trello Ticket:
Additional Notes: Fixes issue where quizzes were not rendering correctly due to incorrect expected response.

Fixes quiz not rendering

---

src/Curriculum/Quiz/Quiz.tsx
src/Curriculum/Survey/Survey.tsx
src/Curriculum/Survey/SurveyStyled.ts
src/__tests__/ModuleList/Survey/__snapshots__/Survey.test.jsx.snap

A few minor changes to the inputs:
* options are wrapped in a div on survey page with a slight indent (less than quiz page)
* option labels wrap the input - they are now clickable
* survey labels are simplified (don't require correctness tag like quiz)
* teal submit buttons

Input Adjustments

---

src/SplashScreen/SplashFooter/SplashFooter.tsx

Trello Ticket: 
If this change is performance related, please …

added style in SplashFooter.tsx that fixed issue of alignment

---

src/App.tsx
src/common/NotFound.tsx

This pull request addresses the issue #111 
- I added a NotFound.tsx file in src/common/
- Added it in App.tsx
- The NotFound page now looks like

Added NotFound file

---

src/SplashScreen/SplashNav/SplashNav.tsx

Sign Up Button on Splash Page

---

src/__tests__/ModuleList/Quiz/Quiz.test.tsx
src/__tests__/ModuleList/Quiz/__snapshots__/Quiz.test.tsx.snap

- If this is a feature, describe the feature that is being added: Converted Quiz.test.jsx to Quiz.test.tsx utilizing TypeScript
**Resolves Issue #126**

Migration of quiz unit test code to TypeScript

---

src/__tests__/ModuleList/Article/Article.test.tsx
src/__tests__/ModuleList/Article/__snapshots__/Article.test.tsx.snap

- If this is a feature, describe the feature that is being added: Migration of Article.test.jsx to TypeScript
**Resolves Issue**: #133

Migration of article tests to TypeScript

---

src/Sidebar/Sidebar.tsx

- If this is a bug fix, what issue is this fixing? This fixed the issue in which if the user clicks on the black area within the side bar, the sidebar now shrinks when the mouse hovers over it and expands when the mouse leaves the area.
**Resolves Issue**: #123

Fixing Sidebar expansion bug

---

src/Emulator/Visuals/Flow/Flow.tsx
src/Sidebar/Sidebar.tsx
src/__tests__/Emulator/Visuals/Flow/__snapshots__/Flow.test.jsx.snap

- If this is a bug fix, what issue is this fixing? This fixes the issue where once nodes are connected the screen jumps and zooms in, but one issue that remains is sometimes when nodes are connected, the screen shifts left or right.
**Resolves Issue**: #124

Fixing emulator screen jump

---

cypress/integration/toynet/emulator.spec.ts
cypress/support/commands.js
cypress/tsconfig.json
package-lock.json
package.json
src/Emulator/EmulatorProvider.tsx
src/Emulator/Visuals/Flow/Flow.tsx
src/Emulator/Visuals/Flow/isValidLink.ts
src/__tests__/Emulator/Visuals/Flow/isValidLink.test.tsx
src/common/utils.ts

Re-adds link validators for the emulator. Now displays a message indicating why the link could not be made in the actions panel.
**Resolves Issue**: closes #170

Link validators

---

src/Emulator/DialogueBox/DialogueBox.tsx
src/Emulator/EmulatorProvider.tsx
src/common/types.ts

For issue #172 
Instead of keeping just messages in array, keep the tuples of [message, color].
Defaults to white.
Closes #172

Added colors to actions

---

.eslintrc.json
src/Emulator/Visuals/Flow/Flow.tsx

Fix for issue #179
closes #179

Add color to error

---

src/Emulator/Instructions/Instructions.tsx
src/__tests__/Emulator/__snapshots__/Emulator.test.tsx.snap
src/common/components/Emulator/InnerSection.tsx

Removed an inline style (padding) for Tasks pane, and then added the style to EmulatorInnerSection for all three panes:Tasks Console, Actions.
**Resolves Issue**: closes #{issue number} (e.g. closes #123).

Better padding in actions / tasks / console

---

.github/workflows/e2e.yml
cypress/docker-compose.dev.yml
cypress/integration/toynet/emulator.spec.ts
docker-compose.dev.yml
docker-compose.yml
package-lock.json
package.json
src/Emulator/Visuals/Flow/Flow.tsx
src/Emulator/Visuals/Visuals.tsx
src/__tests__/Emulator/__snapshots__/Emulator.test.tsx.snap
src/common/components/LoadingAnimation.tsx

Integrations with updated toynet-flask changes. Adds a loading animation.

Loading animation

---

.github/workflows/e2e.yml
docker-compose.dev.yml
docker-compose.yml

Fixes issue where backend gets updated but the frontend is not prepared for the change which causes integration tests to fail.

Deterministic build

---

src/Emulator/Visuals/Flow/Flow.tsx

- Removed onElementsRemove function to disable deleting nodes on click of backspace and/or delete key.
**Resolves Issue**: closes #189

Removed onElementsRemove function to disable deleting nodes on click of backspace/delete key.

---

cypress/docker-compose.dev.yml
docker-compose.dev.yml
package.json
src/Emulator/Console/ConsoleHistoryList.tsx
src/Emulator/Console/ConsoleTerminal.tsx
src/Emulator/Console/DeviceSelector.tsx
src/Emulator/Console/types.ts
src/Emulator/DialogueBox/DialogueBox.tsx
src/Emulator/Drawer/CreateHostView.tsx
src/Emulator/Drawer/CreateRouterView.tsx
src/Emulator/Drawer/InfoTable/HostRows/HostRow.tsx
src/Emulator/Drawer/RouterView/CreateIpBtns.tsx
src/Emulator/Drawer/RouterView/IpList.tsx
src/Emulator/Visuals/Flow/ContextMenus/DeleteConnectionBtn.tsx
src/Emulator/Visuals/Flow/ContextMenus/DeleteNodeButton.tsx
src/Emulator/Visuals/Flow/Flow.tsx
src/Emulator/Visuals/Flow/isInValidLink.ts
src/__tests__/Emulator/Visuals/Flow/isValidLink.test.tsx
src/common/api/topology/hooks.ts
src/common/api/topology/requests.ts
src/common/api/topology/types.ts
src/common/hooks/useSessionStorage.ts
src/common/providers/EmulatorProvider.tsx
src/common/types.ts

Integrates https://github.com/Project-Reclass/toynet-flask/pull/36#issue-1021729600
* Can create proper links
* Can delete nodes
* Proper disabling of inputs
* Adds ability to update a dialogue message
* Adds message when attempting to add or remove a link

Integrates backend updates for links and deletion of nodes

---

src/Curriculum/Value/Value.tsx
src/Curriculum/Value/__tests__/__snapshots__/Value.test.tsx.snap

Fix side nav overlaps value page.
Using Chakra Box component instead of div.
Tests updated.
**Resolves Issue**: closes #224.

Fix side nav overlaps value page

---

cypress/integration/toynet/quiz.spec.ts
package-lock.json
package.json
src/App.tsx
src/Curriculum/Dashboard.tsx
src/Curriculum/Module/Module.tsx
src/Curriculum/Module/SubModule/SubModule.tsx
src/Curriculum/Module/SubModule/__tests__/__snapshots__/SubModule.test.tsx.snap
src/Curriculum/Module/__tests__/Module.test.tsx
src/Curriculum/Module/__tests__/__snapshots__/Module.test.tsx.snap
src/Curriculum/Quiz/Quiz.tsx
src/Curriculum/Quiz/__tests__/Quiz.test.tsx
src/Curriculum/Quiz/__tests__/__snapshots__/Quiz.test.tsx.snap
src/Curriculum/Survey/Survey.tsx
src/Curriculum/Survey/__tests__/Survey.test.tsx
src/Curriculum/Survey/__tests__/__snapshots__/Survey.test.tsx.snap
src/Curriculum/__tests__/__snapshots__/Dashboard.test.tsx.snap
src/common/api/curriculum/quiz/hooks.ts
src/common/api/curriculum/survey/hooks.ts
src/common/api/curriculum/survey/requests.ts
src/common/components/Corner.ts
src/common/types.ts
src/theme.ts

Improves styles of the curriculum dashboard, quiz, and survey pages.

Improves curriculum styles along with survey and quiz

---

cypress/integration/toynet/dashboard.spec.ts
src/Curriculum/Lesson/Lesson.tsx
src/common/api/curriculum/lesson/hooks.ts

Creates a simple lessons page to display lesson slides.

Creates simple lesson page

---

cypress/integration/toynet/value.spec.ts
src/App.tsx
src/Curriculum/Article/Article.tsx
src/Curriculum/Article/ArticleStyles.ts
src/Curriculum/Article/__tests__/__snapshots__/Article.test.tsx.snap
src/Curriculum/Dashboard.tsx
src/Curriculum/Lesson/Lesson.tsx
src/Curriculum/Module/SubModule/SubModule.tsx
src/Curriculum/Module/SubModule/__tests__/SubModule.test.tsx
src/Curriculum/Module/SubModule/__tests__/__snapshots__/SubModule.test.tsx.snap
src/Curriculum/Module/__tests__/__snapshots__/Module.test.tsx.snap
src/Curriculum/Quiz/Quiz.tsx
src/Curriculum/Quiz/__tests__/__snapshots__/Quiz.test.tsx.snap
src/Curriculum/Survey/Survey.tsx
src/Curriculum/Survey/__tests__/__snapshots__/Survey.test.tsx.snap
src/Curriculum/Value/Value.tsx
src/Curriculum/Value/__tests__/__snapshots__/Value.test.tsx.snap
src/Curriculum/Video/Video.tsx
src/Curriculum/__tests__/__snapshots__/Dashboard.test.tsx.snap
src/Emulator/Instructions/Instructions.tsx
src/Emulator/Visuals/Flow/Flow.tsx
src/Emulator/__tests__/__snapshots__/Emulator.test.tsx.snap
src/common/api/curriculum/dashboard/hooks.ts
src/common/components/NavigationButtons.tsx
src/common/components/NavigationWithDivider.tsx
src/common/hooks/useFirstRender.ts
src/common/types/curriculum.ts
src/common/utils.ts

- Refractors create link to utils
- Create navigation components
- Adds navigation to the article page
- Updates article styling
- Creates useFirstRender hook
- Adds video navigation
- Adds lesson navigation
- Adds navigation for emulator and moves restart to Flow 
- Adds navigation to quiz
- Adds navigation to value
- Updates the ">" to use chevron icons
- Updates the value route to use `moduleId`

Adds navigation to the curriculum

---

cypress/integration/toynet/dashboard.spec.ts
src/Curriculum/Dashboard.tsx
src/Curriculum/Module/Module.tsx
src/Curriculum/Module/ModuleList.tsx
src/Curriculum/Module/TooltopIsLocked.tsx
src/Curriculum/Module/__tests__/Module.test.tsx
src/Curriculum/Module/__tests__/__snapshots__/Module.test.tsx.snap
src/common/hooks/useQuerySearch.ts
src/common/utils.ts

- Changes modules to use zero indexed names
- Creates setQueryStringWithoutPageReload utility
- Creates useQuerySearch custom hook
- Refractors TooltipIsLocked to its own file
- Moves state for modules open to url search query

Query search module open

---

cypress/integration/toynet/emulator.spec.ts
src/Emulator/Emulator.tsx
src/Emulator/Instructions/Instructions.tsx
src/Emulator/Visuals/Visuals.tsx
src/Emulator/__tests__/__snapshots__/Emulator.test.tsx.snap
src/common/api/curriculum/lab/useLab.ts
src/common/types/curriculum.ts

Updates the lab to use the toynet-content

Updates the lab to use the toynet-content

---

cypress/integration/toynet/home.spec.ts
src/SplashScreen/SplashHeader/SplashHeader.tsx

The "Try It" button now navigates to the curriculum dashboard.

"Try it" now navigates to curriculm

---

src/Curriculum/Article/__tests__/__snapshots__/Article.test.tsx.snap
src/Curriculum/Quiz/__tests__/__snapshots__/Quiz.test.tsx.snap
src/Curriculum/Survey/__tests__/__snapshots__/Survey.test.tsx.snap
src/Curriculum/Value/__tests__/__snapshots__/Value.test.tsx.snap
src/common/components/NavigationButtons.tsx

Updates the navigation text to use `submodule` instead of `module`.

Updates the navigation text to use submodule

---

src/SplashScreen/SplashFooter/SplashFooter.tsx

Updates the email in the splash screen footer to be the new project
reclass email instead of the outdated email.

Updates the email on the splash screen

---

package-lock.json
package.json
src/Emulator/Visuals/Flow/CustomControls/CustomControls.tsx
src/Emulator/Visuals/Flow/CustomControls/DeviceBtns.tsx
src/Emulator/Visuals/Flow/CustomControls/ToolMenu.tsx
src/Emulator/Visuals/Flow/CustomControls/index.ts
src/Emulator/Visuals/Flow/Flow.tsx

- Adds [react-icons](https://react-icons.github.io/react-icons) dependency which provides more icons than default Chakra icon set.
- Adds a toolbox menu to the upper right of the flow UI.
- Creates new functionality for auto-formatting the topology.

Create auto format topology

---

cypress/integration/toynet/dashboard.spec.ts
src/Curriculum/Lecture/Lecture.tsx
src/common/api/curriculum/article/hooks.ts
src/common/api/curriculum/lecture/useLecture.ts
src/common/components/markdown/MarkdownRenderer/MarkdownRenderer.tsx
src/common/types/curriculum.ts

- Fixes bug where Lecture could not navigate forward
- Disables refetchOnWindowFocus for article
- Disables refetchOnWindowFocus for lecture
- Updates the styling of the markdown render

Several bug fixes and improvements

---

src/Curriculum/Dashboard.tsx
src/Curriculum/Module/SubModule/SubModule.tsx
src/Curriculum/Module/SubModule/__tests__/SubModule.test.tsx
src/Curriculum/Module/SubModule/__tests__/__snapshots__/SubModule.test.tsx.snap
src/Curriculum/Module/SubModule/styled.ts
src/Curriculum/Module/__tests__/__snapshots__/Module.test.tsx.snap
src/Curriculum/__tests__/__snapshots__/Dashboard.test.tsx.snap

- Updated 'Go to submodule >' text with a play button.
- Updated the text in the header.
- Updated a unit test.
**Resolves Issue**: closes #278.

Update the curriculum dashboard to be easier to navigate

---

src/Curriculum/Article/Article.tsx
src/Curriculum/Article/ArticleStyled.ts
src/Curriculum/Article/__tests__/__snapshots__/Article.test.tsx.snap
src/Curriculum/Lecture/Lecture.tsx
src/Curriculum/Lecture/LectureStyled.ts

Fix Y margin for Lecture and Article submodules
Renamed ArticleStyles to ArticleStyled - similarly to other components.
Added new LectureStyled module.
Added 2 new styled components - ArticleContainer and LectureContainer, similarly to how Survey and Quiz submodule are built.
Updated the test snapshot for Article.
**Resolves Issue**: closes #290.

Fix Y margin for Lecture and Article submodules

---

src/Curriculum/Animation/Animation.tsx
src/Curriculum/Animation/AnimationStyled.ts
src/Curriculum/Value/Value.tsx
src/Curriculum/Value/ValueStyled.ts
src/Curriculum/Value/__tests__/__snapshots__/Value.test.tsx.snap

Fix Y margin for Animation and Value submodules
Renamed styled to ValueStyled - similarly to other components.
Added new AnimationStyled module.
Added 2 new styled components - AnimationContainer and ValueContainer, similarly to how Survey and Quiz submodule are built.
Updated the test snapshot for Value.
**Resolves Issue**: closes #294.

Fix Y margin for Animation and Value submodules

---

cypress/docker-compose.dev.yml
docker-compose.dev.yml
docker-compose.yml
task-definition.json

Updating the backend to the latest working version for deployment and for development workflows.

Update flask version

---

cypress/integration/toynet/emulator.spec.ts
src/Emulator/Instructions/Instructions.tsx

- Removed the link of 'Back to Site' from the instruction panel.
- Updated snapshots.
**Resolves Issue**: closes #263.

Remove the 'Back to Site' link from the instruction panel.

---

src/Curriculum/Article/__tests__/__snapshots__/Article.test.tsx.snap
src/Curriculum/Quiz/__tests__/__snapshots__/Quiz.test.tsx.snap
src/Curriculum/Survey/__tests__/__snapshots__/Survey.test.tsx.snap
src/Curriculum/Value/__tests__/__snapshots__/Value.test.tsx.snap
src/common/components/NavigationButtons.tsx

Changed the navigation buttons to not include submodule
**Resolves Issue**: closes #{288} (e.g. closes #288).

Changed navigation button text

---

task-definition.json

Reverts Project-Reclass/toynet-react#321

Revert "Update task-definition.json"

---

docker-compose.yml

This PR allows you to run `docker-compose up` on ARM and have it work :) 
**Resolves Issue**: closes #{issue number} (e.g. closes #123).

Support arm in `docker-compose.yml`

---

package.json
src/Curriculum/Quiz/Quiz.tsx
src/Curriculum/Quiz/__tests__/__snapshots__/Quiz.test.tsx.snap
src/Curriculum/Survey/Survey.tsx
src/Curriculum/Survey/__tests__/__snapshots__/Survey.test.tsx.snap
src/Emulator/Drawer/CreateHostView.tsx
src/Emulator/Drawer/CreateRouterView.tsx
src/Emulator/__tests__/__snapshots__/Emulator.test.tsx.snap
src/common/components/LoadingSpinner.tsx

Update src/Curriculum/Survey/Survey.tsx to not use style #200
Update src/Curriculum/Quiz/Quiz.tsx to not use style #199
style={{ margin: '5px' }} to margin='5px'
Update src/common/components/LoadingSpinner.tsx to not use style #198
<div style={{ position: 'relative', height: '100%' }}> to <Box position='relative' height='100%'>
update Snapshot
npm run check-types
pass
npm run style:check
✖ 2 problems (0 errors, 2 warnings)
npm run style:fix
pass
npm run test
Test Suites: 30 passed, 30 total
Tests:       110 passed, 110 total
Snapshots:   19 passed, 19 total
Time:        24.734 s
Ran all test suites.
Commited and made a Pull Request
Now let's cross our fingers!!!! and Happy Thankgiving!!!
**Resolves Issue**: closes #198.
**Resolves Issue**: closes #199.
**Resolves Issue**: closes #200.

No inline style

---

package.json
src/Emulator/Drawer/CreateHostView.tsx
src/Emulator/Drawer/CreateRouterView.tsx

File: CreateHostView.tsx
Line 153: fontFamily='monospace'
File: CreateRouterView.tsx
Line 148: fontFamily='monotspace'
No Snapshots to update
npm run check-types
pass
npm run style:check
✖ 2 problems (0 errors, 2 warnings)
npm run style:fix
pass
npm run test
Test Suites: 30 passed, 30 total
Tests:       110 passed, 110 total
Snapshots:   19 passed, 19 total
Time:        13.411 s
Ran all test suites.
Commited and made a Pull Request
Now let's cross our fingers!!!! and Happy Thankgiving!!!
**Resolves Issue**: closes #287 .

Change the font of IP addresses to be monospace #287 
